services:
  postgres:
    image: postgres:15
    container_name: stockpro-postgres-dev
    restart: always
    env_file:
      - ./stockpro-backend/.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    networks:
      - stockpro-dev-network

  backend:
    build:
      context: ./stockpro-backend
      dockerfile: Dockerfile.dev
    container_name: stockpro-backend-dev
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - ./stockpro-backend/.env
    volumes:
      - ./stockpro-backend:/app
    depends_on:
      - postgres
    networks:
      - stockpro-dev-network
    stdin_open: true
    tty: true
    # Generate Prisma client and start in development mode
    command: sh -c "pnpm prisma generate && pnpm run start:dev"

  frontend:
    build:
      context: ./stockpro-frontend
      dockerfile: Dockerfile.dev
    container_name: stockpro-frontend-dev
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000"
    volumes:
      - ./stockpro-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - stockpro-dev-network
    stdin_open: true
    tty: true
    command: pnpm run dev
  prisma-studio:
    build:
      context: ./stockpro-backend
      dockerfile: Dockerfile.dev

    container_name: stockpro-prisma-studio-dev
    restart: always
    ports:
      - '5555:5555'
    env_file:
      - ./stockpro-backend/.env
    volumes:
      - ./stockpro-backend:/app
    depends_on:
      - postgres
    networks:
      - stockpro-dev-network
    command: sh -c "pnpm prisma generate && npx prisma studio --hostname 0.0.0.0 --port 5555"

volumes:
  pgdata_dev:


networks:
  stockpro-dev-network:
    driver: bridge
